//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicess
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string accesslevel { get; set; }
        public string parent { get; set; }
    }
}
